// Static asset table. All assets are original, generated by scripts/gen-models.mjs and scripts/gen-audio.mjs.
export const MODELS = {
  gems: [
    require("../../assets/models/gem_red.glb"),
    require("../../assets/models/gem_blue.glb"),
    require("../../assets/models/gem_green.glb"),
    require("../../assets/models/gem_purple.glb"),
    require("../../assets/models/gem_gold.glb"),
  ],
  prism: require("../../assets/models/gem_prism.glb"),
  surgeAura: require("../../assets/models/surge_aura.glb"),
  platform: require("../../assets/models/platform.glb"),
  terrain: require("../../assets/models/terrain.glb"),
  propsBack: require("../../assets/models/props_back.glb"),
  propsLeft: require("../../assets/models/props_left.glb"),
  propsRight: require("../../assets/models/props_right.glb"),
  portalCore: require("../../assets/models/portal_core.glb"),
  waterfall: require("../../assets/models/waterfall.glb"),
  bloom: require("../../assets/models/bloom.glb"),
  vines: require("../../assets/models/vines.glb"),
  glowCluster: require("../../assets/models/glow_cluster.glb"),
  groundShadow: require("../../assets/models/ground_shadow.glb"),
};

export const TEXTURES = {
  spark: require("../../assets/textures/spark.png"),
  ringGlow: require("../../assets/textures/ring_glow.png"),
  environment: require("../../assets/textures/studio_forest.hdr"),
  tableWood: require("../../assets/textures/table_wood.png"),
  roomBackdrop: require("../../assets/textures/room_backdrop.png"),
};

/** Display colours per crystal kind (particles, UI accents). Index = CrystalType. */
export const CRYSTAL_COLORS = ["#ff3b4e", "#3d7bff", "#22d36a", "#b05cff", "#ffc53d"];
export const CRYSTAL_NAMES = ["Ember Heart", "Deep Diamond", "Leaf Emerald", "Spiral Amethyst", "Sun Star"];
