// Static asset table. All assets are original, generated by scripts/gen-models.mjs and scripts/gen-audio.mjs.
export const MODELS = {
  gems: [
    require("../../assets/models/gem_red.glb"),
    require("../../assets/models/gem_blue.glb"),
    require("../../assets/models/gem_green.glb"),
    require("../../assets/models/gem_purple.glb"),
    require("../../assets/models/gem_gold.glb"),
  ],
  prism: require("../../assets/models/gem_prism.glb"),
  surgeAura: require("../../assets/models/surge_aura.glb"),
  platform: require("../../assets/models/platform.glb"),
  terrain: require("../../assets/models/terrain.glb"),
  propsBack: require("../../assets/models/props_back.glb"),
  propsLeft: require("../../assets/models/props_left.glb"),
  propsRight: require("../../assets/models/props_right.glb"),
  portalCore: require("../../assets/models/portal_core.glb"),
  waterfall: require("../../assets/models/waterfall.glb"),
  bloom: require("../../assets/models/bloom.glb"),
  vines: require("../../assets/models/vines.glb"),
  glowCluster: require("../../assets/models/glow_cluster.glb"),
  groundShadow: require("../../assets/models/ground_shadow.glb"),
  // CC-BY 3.0 models from Poly Pizza – credited in ASSET_LICENSES.md and the Settings screen
  dragonRed: require("../../assets/models/dragon_red.glb"),
  dragonGreen: require("../../assets/models/dragon_green.glb"),
  flameTurret: require("../../assets/models/flame_turret.glb"),
};

/**
 * Optimised Meshy GLB files (built by tools/asset-pipeline). The game does NOT load these (it uses the baked
 * in-memory geometry in meshyMeshes.ts, since a GLB per crystal crashed Viro): only the /dev/models
 * comparison page loads them.
 */
export const MESHY_MODELS = {
  gem_red: require("../../assets/models/meshy/gem_red.glb"),
  gem_blue: require("../../assets/models/meshy/gem_blue.glb"),
  gem_green: require("../../assets/models/meshy/gem_green.glb"),
  gem_purple: require("../../assets/models/meshy/gem_purple.glb"),
  gem_gold: require("../../assets/models/meshy/gem_gold.glb"),
  gem_prism: require("../../assets/models/meshy/gem_prism.glb"),
  gem_relic: require("../../assets/models/meshy/gem_relic.glb"),
  surge_aura: require("../../assets/models/meshy/surge_aura.glb"),
};

/** 1024 px base-colour maps of the Meshy realm islands (tools/asset-pipeline/bake-islands.mjs). */
export const ISLAND_TEXTURES: Record<string, number> = {
  verdant: require("../../assets/textures/meshy/island_verdant.jpg"),
  canyon: require("../../assets/textures/meshy/island_canyon.jpg"),
  tide: require("../../assets/textures/meshy/island_tide.jpg"),
  sky: require("../../assets/textures/meshy/island_sky.jpg"),
  hollow: require("../../assets/textures/meshy/island_hollow.jpg"),
  caverns: require("../../assets/textures/meshy/island_caverns.jpg"),
  frozen: require("../../assets/textures/meshy/island_frozen.jpg"),
  solar: require("../../assets/textures/meshy/island_solar.jpg"),
  ember: require("../../assets/textures/meshy/island_ember.jpg"),
  void: require("../../assets/textures/meshy/island_void.jpg"),
};

/** Base-colour maps of the game-LOD Meshy crystals (tools/asset-pipeline/bake-game.mjs), 256 px JPEG. */
export const MESHY_TEXTURES: Record<string, number> = {
  gem_red: require("../../assets/textures/meshy/gem_red.jpg"),
  gem_blue: require("../../assets/textures/meshy/gem_blue.jpg"),
  gem_green: require("../../assets/textures/meshy/gem_green.jpg"),
  gem_purple: require("../../assets/textures/meshy/gem_purple.jpg"),
  gem_gold: require("../../assets/textures/meshy/gem_gold.jpg"),
  gem_prism: require("../../assets/textures/meshy/gem_prism.jpg"),
  gem_relic: require("../../assets/textures/meshy/gem_relic.jpg"),
  surge_aura: require("../../assets/textures/meshy/surge_aura.jpg"),
};

export const TEXTURES = {
  spark: require("../../assets/textures/spark.png"),
  ringGlow: require("../../assets/textures/ring_glow.png"),
  // effect sprites generated by tools/asset-pipeline/gen-fx.mjs
  fxShard: require("../../assets/textures/fx_shard.png"),
  fxGlow: require("../../assets/textures/fx_glow.png"),
  fxStar: require("../../assets/textures/fx_star.png"),
  // CC0 studio HDRI (Poly Haven "Studio Small 09", resized to 512×256): soft boxes give crystal facets real highlights
  environment: require("../../assets/textures/studio_hdri.hdr"),
  tableWood: require("../../assets/textures/table_wood.png"),
  roomBackdrop: require("../../assets/textures/room_backdrop.png"),
  sky: require("../../assets/textures/sky_panorama.png"),
  cloudSea: require("../../assets/textures/cloud_sea.png"),
};

/**
 * CC0 photo-scanned PBR materials from ambientCG (see ASSET_LICENSES.md), resized to 512 px by
 * scripts/process-textures.mjs. c = colour, n = OpenGL normal, r = roughness.
 */
const pbr = (c: number, n: number, r: number) => ({ c, n, r });
export const PBR = {
  grass: pbr(require("../../assets/textures/pbr/grass_c.jpg"), require("../../assets/textures/pbr/grass_n.jpg"), require("../../assets/textures/pbr/grass_r.jpg")),
  moss: pbr(require("../../assets/textures/pbr/moss_c.jpg"), require("../../assets/textures/pbr/moss_n.jpg"), require("../../assets/textures/pbr/moss_r.jpg")),
  rock: pbr(require("../../assets/textures/pbr/rock_c.jpg"), require("../../assets/textures/pbr/rock_n.jpg"), require("../../assets/textures/pbr/rock_r.jpg")),
  cliff: pbr(require("../../assets/textures/pbr/cliff_c.jpg"), require("../../assets/textures/pbr/cliff_n.jpg"), require("../../assets/textures/pbr/cliff_r.jpg")),
  rockMoss: pbr(require("../../assets/textures/pbr/rockMoss_c.jpg"), require("../../assets/textures/pbr/rockMoss_n.jpg"), require("../../assets/textures/pbr/rockMoss_r.jpg")),
  rockDark: pbr(require("../../assets/textures/pbr/rockDark_c.jpg"), require("../../assets/textures/pbr/rockDark_n.jpg"), require("../../assets/textures/pbr/rockDark_r.jpg")),
  sand: pbr(require("../../assets/textures/pbr/sand_c.jpg"), require("../../assets/textures/pbr/sand_n.jpg"), require("../../assets/textures/pbr/sand_r.jpg")),
  snow: pbr(require("../../assets/textures/pbr/snow_c.jpg"), require("../../assets/textures/pbr/snow_n.jpg"), require("../../assets/textures/pbr/snow_r.jpg")),
  ice: pbr(require("../../assets/textures/pbr/ice_c.jpg"), require("../../assets/textures/pbr/ice_n.jpg"), require("../../assets/textures/pbr/ice_r.jpg")),
  lava: pbr(require("../../assets/textures/pbr/lava_c.jpg"), require("../../assets/textures/pbr/lava_n.jpg"), require("../../assets/textures/pbr/lava_r.jpg")),
  bark: pbr(require("../../assets/textures/pbr/bark_c.jpg"), require("../../assets/textures/pbr/bark_n.jpg"), require("../../assets/textures/pbr/bark_r.jpg")),
  dirt: pbr(require("../../assets/textures/pbr/dirt_c.jpg"), require("../../assets/textures/pbr/dirt_n.jpg"), require("../../assets/textures/pbr/dirt_r.jpg")),
  gravel: pbr(require("../../assets/textures/pbr/gravel_c.jpg"), require("../../assets/textures/pbr/gravel_n.jpg"), require("../../assets/textures/pbr/gravel_r.jpg")),
  paving: pbr(require("../../assets/textures/pbr/paving_c.jpg"), require("../../assets/textures/pbr/paving_n.jpg"), require("../../assets/textures/pbr/paving_r.jpg")),
};
export type PbrId = keyof typeof PBR;

/** Display colours per crystal kind (particles, UI accents). Index = CrystalType. */
export const CRYSTAL_COLORS = ["#ff5a2a", "#2f7bff", "#1fd06c", "#9b4dff", "#ffc53d"];
export const CRYSTAL_NAMES = ["Ember Core", "Tide Sapphire", "Leaf Emerald", "Void Amethyst", "Solar Shard"];
