// GENERATED by tools/asset-pipeline/bake-islands.mjs - do not edit.
// Each realm is required lazily, so only the islands actually shown are evaluated at runtime.
import type { MeshyIsland } from "./types";
export type { MeshyIsland } from "./types";
const LOADERS: Record<string, () => MeshyIsland> = {
  canyon: () => require("./canyon").ISLAND,
  ember: () => require("./ember").ISLAND,
  sky: () => require("./sky").ISLAND,
  tide: () => require("./tide").ISLAND,
  verdant: () => require("./verdant").ISLAND,
};
export const MESHY_ISLAND_REALMS = ["canyon","ember","sky","tide","verdant"];
const cache = new Map<string, MeshyIsland>();
export function meshyIsland(realm: string): MeshyIsland | null {
  let m = cache.get(realm);
  if (!m && LOADERS[realm]) cache.set(realm, (m = LOADERS[realm]()));
  return m ?? null;
}
