// Raw Meshy GLB -> in-memory game geometry (src/render/meshyMeshes.ts) + one small base-colour JPEG per model
// (assets/textures/meshy/). Only the base colour map is kept: Viro materials take a diffuse texture, normal maps
// render black on Viro geometry, and the emissive/metal-rough maps have no Viro equivalent.
//   node bake-game.mjs [out_name ...]
import { mkdirSync, writeFileSync, statSync } from "node:fs";
import { NodeIO } from "@gltf-transform/core";
import { ALL_EXTENSIONS } from "@gltf-transform/extensions";
import { prune, dedup, textureCompress, flatten } from "@gltf-transform/functions";
import sharp from "sharp";
import { ASSETS, GAME_LOD, GAME_MESH_FILE, GAME_TEX_DIR, SRC_DIR, slug } from "./config.mjs";
import { bake } from "./lib.mjs";
import { decimateTextured } from "./reproject.mjs";

mkdirSync(GAME_TEX_DIR, { recursive: true });
const io = new NodeIO().registerExtensions(ALL_EXTENSIONS);
const only = new Set(process.argv.slice(2));
const r = (v, d) => Math.round(v * 10 ** d) / 10 ** d;
const out = {};
console.log("name         tris  verts  bridge#   islands  tex KB   (classic bridge# for comparison)");
const CLASSIC = { gem_red: 2016, gem_blue: 5880, gem_green: 2688, gem_purple: 3024, gem_gold: 2016, gem_prism: 420, gem_relic: 3528, surge_aura: 5712 };
for (const spec of ASSETS) {
  if (only.size && !only.has(spec.out)) continue;
  const lod = GAME_LOD[spec.out];
  const doc = await io.read(`${SRC_DIR}${slug(spec.name)}.glb`);
  await doc.transform(flatten());
  for (const m of doc.getRoot().listMaterials()) { m.setNormalTexture(null); m.setOcclusionTexture(null); m.setEmissiveTexture(null); m.setMetallicRoughnessTexture(null); }
  bake(doc, spec); // orient, centre and scale the SOURCE so the decimated mesh lands in game units
  await doc.transform(textureCompress({ encoder: sharp, resize: [lod.tex, lod.tex], targetFormat: "jpeg", quality: 80 }), dedup(), prune());
  const prim = doc.getRoot().listMeshes()[0].listPrimitives()[0];
  const m = await decimateTextured({
    P: prim.getAttribute("POSITION").getArray(), N: prim.getAttribute("NORMAL").getArray(),
    U: prim.getAttribute("TEXCOORD_0").getArray(), I: prim.getIndices().getArray(),
  }, lod.tris);
  writeFileSync(`${GAME_TEX_DIR}${spec.out}.jpg`, doc.getRoot().listMaterials()[0].getBaseColorTexture().getImage());
  out[spec.out] = { v: m.v.map((x) => r(x, 4)), n: m.n.map((x) => r(x, 3)), t: m.t.map((x) => r(x, 4)), i: m.i };
  const bridge = m.stats.verts * 8 + m.stats.tris * 3;
  console.log(`${spec.out.padEnd(11)} ${String(m.stats.tris).padStart(5)} ${String(m.stats.verts).padStart(6)} ${String(bridge).padStart(8)}  ${String(m.stats.islands).padStart(7)}  ${(statSync(`${GAME_TEX_DIR}${spec.out}.jpg`).size / 1024).toFixed(0).padStart(6)}    (${CLASSIC[spec.out]})`);
}
if (only.size) console.log("(partial run: not rewriting meshyMeshes.ts)");
else {
  const body = Object.entries(out).map(([k, m]) => `  ${JSON.stringify(k)}: ${JSON.stringify(m)},`).join("\n");
  writeFileSync(GAME_MESH_FILE, `// GENERATED by tools/asset-pipeline/bake-game.mjs - do not edit. Game-LOD Meshy crystals as indexed geometry:
// v = xyz, n = unit normals, t = uv (glTF convention, v down), i = triangle indices. Textures: assets/textures/meshy/<name>.jpg.
export interface MeshyMesh { v: number[]; n: number[]; t: number[]; i: number[] }
export const MESHY_MESHES: Record<string, MeshyMesh> = {
${body}
};
`);
  console.log("wrote", GAME_MESH_FILE, (statSync(GAME_MESH_FILE).size / 1024).toFixed(0), "KB");
}
